import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/navigation/Navbar";
import Sidebar from "@/components/navigation/sidebar/Sidebar";
import NavbarProvider from "@/context/NavbarProvider";
import ThemeProvider from "@/context/ThemeProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}dark:text-colorDarkThird dark:bg-colorDarkFirst antialiased`}
        suppressHydrationWarning
      >
        <ThemeProvider>
          <NavbarProvider>
            <Navbar />
            <div className="w-full flex gap-x-2 max-w-7xl mx-auto px-4 sm:px-5 md:px-8 py-10">
              <Sidebar />
              <div className="w-full">{children}</div>
            </div>
          </NavbarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
